var countyabbr = {
  Bedfordshire: "Beds",
  Berkshire: "Berks",
  Buckinghamshire: "Bucks",
  Cambridgeshire: "Cambs",
  Cumberland: "Cumb",
  Derbyshire: "Derbs",
  Gloucestershire: "Glos",
  Hampshire: "Hants",
  Herefordshire: "Heref",
  Hertfordshire: "Herts",
  Huntingdonshire: "Hunts",
  Lancashire: "Lancs",
  Leicestershire: "Leics",
  Lincolnshire: "Lincs",
  Northamptonshire: "Northants",
  Northumberland: "Northumb",
  Nottinghamshire: "Notts",
  Oxfordshire: "Oxon",
  Shropshire: "Shrops",
  Staffordshire: "Staffs",
  Warwickshire: "Warks",
  Westmorland: "Westm",
  Wiltshire: "Wilts",
  Worcestershire: "Worcs",
  Yorkshire: "Yorks",
  Breconshire: "Brecks",
  Cardiganshire: "Cards",
  Carmarthenshire: "Carms",
  Flintshire: "Flints",
  Glamorgan: "Glam",
  Montgomeryshire: "Mont",
  Pembrokeshire: "Pembs",
  Radnorshire: "Rads",
  Massachusetts: "MA",
  Pennsylvania: "PA",
  "New York": "NY",
  Maryland: "MD",
  "New Jersey": "NJ",
  "Delaware": "DE",
  Virginia: "VA",
  "North Carolina": "NC",
  "South Carolina": "SC",
  Georgia: "GA",
  Florida: "FL",
  Alabama: "AL",
  Louisiana: "LA",
  Texas: "TX",
  Illinois: "IL",
  Michigan: "MI",
  Washington: "WA",
  Hawaii: "HI",
  "District of Columbia": "DC",
  Tennessee: "TN",
  Arkansas: "AR",
  Connecticut: "CT",
  "Australian Capital Territory": "ACT",
  "New South Wales": "NSW",
  "Northern Territory": "NT",
  Queensland: "Qld",
  "South Australia": "SA",
  Victoria: "Vic",
  "Western Australia": "WA",
  Tasmania: "Tas"
}

module.exports = countyabbr;